### ISSUE TITLE
'LWRP' does not exist in the namespace 'UnityEngine.Experimental.Rendering'

### ISSUE THREAD

**Issue by kndol** [Unity-Technologies/arfoundation-samples#159]
Unity version:  2019.1.6f1
LWRP version: 5.7.2
ARFoundation-samples branch: lwrp-support-2019.1-with-2.1

When I load the 'ARFoundation-samples' project, I met errors:

Assets\LWRPSupport\LWRPBackgroundRenderPass.cs(4,42): error CS0234: The type or namespace name 'LWRP' does not exist in the namespace 'UnityEngine.Experimental.Rendering' (are you missing an assembly reference?)

Assets\LWRPSupport\LWRPBeforeCameraRender.cs(8,58): error CS0246: The type or namespace name 'IBeforeRender' could not be found (are you missing a using directive or an assembly reference?)

Assets\LWRPSupport\LWRPBackgroundRenderPass.cs(42,30): error CS0115: 'LWRPBackgroundRenderPass.Execute(ScriptableRenderer, ScriptableRenderContext, ref RenderingData)': no suitable method found to override

Assets\LWRPSupport\LWRPBackgroundRenderPass.cs(8,18): error CS0534: 'LWRPBackgroundRenderPass' does not implement inherited abstract member 'ScriptableRenderPass.Execute(ScriptableRenderContext, ref RenderingData)'

**Comment by ShogoTakagi** [comment]
The same problem happened to me.

Solution:
Update LWRP package
5.7.2  -> 5.16.1

**Comment by ebeland** [comment]
I am also experiencing this issue trying to load the project.

**Comment by tdmowrer** [comment]
That branch was designed to work with LWRP 5.6.1 and is not compatible with 5.7.2. We'll need to do some work on our end to upgrade the sample. In the meantime, can you use LWRP 5.6.1?

**Comment by AlterHowdegen** [comment]
Can't downgrade below 5.7.2 with Unity 2019.1, so that does not seem to be an option.

Currently, non of the latest versions (Unity + LWRP + ARFoundation) seem to work together...

**Comment by tdmowrer** [comment]
> Can't downgrade below 5.7.2 with Unity 2019.1, so that does not seem to be an option.

5.6.1 is compatible with 2019.1b4 and later. Indeed, it does not appear in the package manager window. I'm not sure why that is, but you can manually edit your `Packages/manifest.json` to set it to 5.6.1.

**Comment by AlterHowdegen** [comment]
Cool, will try and report back.

**Comment by AlterHowdegen** [comment]
Unity 2019.1.0f2
ARF 2.1.0
LWRP 5.6.1

Throws a couple compilation errors mainly realted to 'ARHumanBodyManager' etc.

Deleting all scripts (was only interested in LWRPSupport folder) removes compilation errors and properly works on device.

**Comment by TheBricktop** [comment]
please update it to newest release. LWRP and shadergraph is absolutely essential in my projects.

**Comment by ebeland** [comment]
Can you point me to a stable sample ARFoundation app and version of Unity that can achieve all of these goals.

#1 run on iOs 12 so I can launch my product before September.
#2 Not throw obscure compiler references that there is no documentation on.
#3 demonstrate proper lighting in AR
#4 demonstrate face tracking.

I’ve tried numerous combinations of editor and sample app.  Everything seems to be broken or in preview currently.

Thanks,

**Comment by MaryamSaeed** [comment]
any news on this?

**Comment by tdmowrer** [comment]
Prior to ARFoundation 3.0, LWRP support only worked in very specific cases (i.e., the branch mentioned at the top of this thread) and was not very well supported.

LWRP (now called "Universal RP") is supported much better by ARFoundation 3.0; [here is the documentation](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/manual/ar-camera-background-with-scriptable-render-pipeline.html). This requires Unity 2019.2 or later.

@ebeland 
> Can you point me to a stable sample ARFoundation app and version of Unity that can achieve all of these goals...

If the 4 goals you mentioned are the only requirements (i.e., no LWRP support) then I recommend Unity 2019.2 and ARFoundation 2.1. Unity 2019.2 is the current stable release (i.e., it is not alpha or beta) and ARFoundation 2.1 is "verified" (i.e., not preview).

If you do need LWRP/Universal RP support, then I recommend Unity 2019.2 and ARFoundation 3.0 (currently in preview).
