### ISSUE TITLE
lwrp-support-2019.1-with-2.1 does not work with LWRP 5.7.2

### ISSUE THREAD

**Issue by mutaphysis** [Unity-Technologies/arfoundation-samples#206]
Hi all,

The LWRPBackgroundRenderPass & LWRPBeforeCameraRender are only compatible with LWRP `5.6.1`. 

The verified version of the package LWRP `5.7.2` removed the old experimental APIs and causes compilation problems:

```
Assets/vendor/ARKit/LWRPSupport/LWRPBackgroundRenderPass.cs(4,42): error CS0234: The type or namespace name 'LWRP' does not exist in the namespace 'UnityEngine.Experimental.Rendering' (are you missing an assembly reference?)
Assets/vendor/ARKit/LWRPSupport/LWRPBeforeCameraRender.cs(4,42): error CS0234: The type or namespace name 'LWRP' does not exist in the namespace 'UnityEngine.Experimental.Rendering' (are you missing an assembly reference?)
Assets/vendor/ARKit/LWRPSupport/LWRPBeforeCameraRender.cs(8,58): error CS0246: The type or namespace name 'IBeforeRender' could not be found (are you missing a using directive or an assembly reference?)
Assets/vendor/ARKit/LWRPSupport/LWRPBackgroundRenderPass.cs(42,30): error CS0115: 'LWRPBackgroundRenderPass.Execute(ScriptableRenderer, ScriptableRenderContext, ref RenderingData)': no suitable method found to override
Assets/vendor/ARKit/LWRPSupport/LWRPBackgroundRenderPass.cs(8,18): error CS0534: 'LWRPBackgroundRenderPass' does not implement inherited abstract member 'ScriptableRenderPass.Execute(ScriptableRenderContext, ref RenderingData)'
```

My quick trials in updating the code failed, as the API changes seem to be substantial - e.g. no more IBeforeRender.

Are there any plans supporting the non-experimental LWRP APIs?

**Comment by DiannaUnity** [comment]
From our dev:
> There is a significant LWRP API change between 5.6.2 and 5.7.2.    
>Currently, we are focusing on getting ARFoundation working with the new URP package.

**Comment by mutaphysis** [comment]
Thanks for the quick answer @DiannaUnity - do you have a rough idea on how far away this is? Just weeks or months would be sufficient to allow me estimate the impact for a project I am currently working on.

**Comment by tjukic** [comment]
> From our dev:
> 
> > There is a significant LWRP API change between 5.6.2 and 5.7.2.
> > Currently, we are focusing on getting ARFoundation working with the new URP package.

URP package is available to public?

**Comment by MaryamSaeed** [comment]
@mutaphysis i think you need to update the namespaces used in this script

**Comment by mutaphysis** [comment]
This wasn't my script. It was from this repo. It was in the now deleted branch `lwrp-support-2019.1-with-2.1` :

https://github.com/Unity-Technologies/arfoundation-samples/blob/ded901dfa8403c610e73a8a9b58232964cca6ef7/Assets/LWRPSupport/LWRPBeforeCameraRender.cs

**Comment by mutaphysis** [comment]
I guess this issue could be closed, as LWRP is/will be replaced with URP, and there are no samples anymore. I guess some kind of official answer would have been nice, but the removal of the branch was a kind of answer 👯‍♂

**Comment by mutaphysis** [comment]
https://forum.unity.com/threads/configuring-ar-foundation-3-0-0-preview-to-work-with-lwrp-or-urp.736583/ for anyone looking for an answer on how to set things up.
