### ISSUE TITLE
Xcode build ends up with Error in UnityARKit.m class with following suggestion: Use of undeclared identifier 'kCLErrorDomain'; did you mean 'SCNErrorDomain'?

### ISSUE THREAD

**Issue by muxavir** [Unity-Technologies/arfoundation-samples#775]
I am using Branch 4.1, Unity 2020.3.1f1 and Xcode Version 11.4.1 (11E503a). Whenever I build it ends up with error: Use of undeclared identifier 'kCLErrorDomain'; did you mean 'SCNErrorDomain'? in line 91 UnityARKit.m class.

Let me know with the solution. 
Thanks
![Screenshot 2021-03-25 at 3 16 52 AM](https://user-images.githubusercontent.com/8582320/112390723-8c72d700-8d18-11eb-8b9c-800698b53c3d.png)

**Comment by tdmowrer** [comment]
`kCLErrorDomain` is defined in `CoreLocation/CLErrorDomain.h`. In Xcode 12+, ARKit uses CoreLocation to support geo anchors, so including the ARKit header (`ARKit/ARKit.h`) brings in CoreLocation. Is there anything preventing you from updating to Xcode 12?

**Comment by muxavir** [comment]
Switching from 4.1 -> 4.0 branch worked somehow. However seems like I need to update Xcode 11 -> 12 to work on 4.1 or later branches. 

Thanks for quick response.

**Comment by tdmowrer** [comment]
The 4.1 branch has a sample that uses ARKit's geo anchors, which requires types in the CoreLocation framework header. Earlier releases predate this feature and therefore don't have the problem.

Xcode 12 was released last June 22, 9 months ago. If there are blockers which prevent you from upgrading, could you let us know what they are so that we can determine whether we need to invest more time in supporting older versions of Xcode?

**Comment by muxavir** [comment]
I have not updated my OS from 10.15.4 yet, so I think this should be updated to use XCode 12.
